# Generated by Django 3.1.3 on 2020-11-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_item', models.CharField(max_length=100)),
                ('date_item', models.DateTimeField()),
                ('todo_id', models.IntegerField()),
            ],
        ),
    ]
